### ISSUE TITLE
v0.11.0

### ISSUE THREAD

**Issue by morrys** [morrys/react-relay-offline#22]
* [x] upgrade of the library that manages the persistence of the stores https://github.com/morrys/wora/issues/14
 * [x] `retry` should check if environment is online. #20 
 * [x] Improve the handling of Loading in react-native #21
