### ISSUE TITLE
release: v1.0.0-rc.4

### ISSUE THREAD

**Issue by morrys** [morrys/react-relay-offline#24]
* [x] update dependency "react-relay >= 6.0.0"
 * [x] update dependency "react: >=16.9.0"
 * [x] possibility to use hooks (for now I add the dependency to relay-hooks and create useQueryOffline)
 * [x] fix subscribe store-only & store-or-network https://github.com/morrys/react-relay-offline/issues/26
 * [x] complete the SSR example in nextjs https://github.com/morrys/react-relay-offline/issues/23
 * [x] rename the CACHE_FIRST policy in store-or-network
 * [x] better management of the offline configuration https://github.com/morrys/wora/issues/14
 * [x] update dependency wora/cache-persist 2.0.4 (small fix)
 * [x] release relay-hooks 2.0.0 https://github.com/relay-tools/relay-hooks/issues/45

branch react-relay-offline: https://github.com/morrys/react-relay-offline/tree/relay-hooks
branch relay-hooks: https://github.com/relay-tools/relay-hooks/tree/2.0.0
wora: https://github.com/morrys/wora/

**Comment by morrys** [comment]
**For the details released by the wora libraries, follow the links to their releases:**

## wora/offline-first 2.0.2
https://github.com/morrys/wora/releases/tag/offline-first%402.0.2

## wora/relay-offline 2.0.2
https://github.com/morrys/wora/releases/tag/relay-offline%402.0.2

## wora/relay-store2.0.2
https://github.com/morrys/wora/releases/tag/relay-store%402.0.2

# react-relay-offline 1.0.0-rc.3

In the branch I updated the readme.md:
https://github.com/morrys/react-relay-offline/blob/relay-hooks/README.md

Updated the nextjs / todo-updater sample projects:
https://github.com/morrys/offline-examples/tree/master/relay

**Comment by morrys** [comment]
version 1.0.0 released https://github.com/morrys/react-relay-offline/releases/tag/v1.0.0
